image: docker:stable

services:
  - docker:dind

stages:
  # - test
   - build
# test:
#   stage: test
#   before_script:
#     - docker build -t raju6713/docker-learn-react -f Dockerfile.dev .
#   script:
#     - echo "Testing App"
#     - docker run -e CI=true raju6713/docker-learn-react npm run test
#     - echo "Test successfully!"
#   tags: 
#     - ci

build:
  stage: build
  only:
    - master
  script:
    - apk add --no-cache docker-compose
    - echo "REACT_APP_DICTIONARY_API=$REACT_APP_DICTIONARY_API \n REACT_APP_WORDTRACKER_API=$REACT_APP_WORDTRACKER_API \n NGINX_WORD_TRACKER_API=$NGINX_WORD_TRACKER_API \n NGINX_PORT=$NGINX_PORT" > $(pwd)/.env
    - cat $(pwd)/.env
    - docker-compose up --build -d lincolns_dictionary
    - echo cleaning images
    - docker system prune -f
  tags:
    - ci
